"""
Scripted walkthroughs: an ordered list of beats per concept.

Each beat has narration text, a caption, and a cue. The cue keys (slider, highlight,
settle, step) are read by the matching renderer in sceneFrames.tsx to drive the frame.
"""

WALKTHROUGHS = {
    "compound-interest": [
        {"text": "Here's a thousand dollars, saved for twenty years. Watch how it grows.",
         "caption": "Start: $1,000", "cue": {"slider": 0.06, "highlight": "actual"}},
        {"text": "If interest were simple -- the same dollars added each year -- you'd follow this straight gray line.",
         "caption": "Straight-line intuition", "cue": {"slider": 0.06, "highlight": "intuition"}},
        {"text": "But each month's interest also earns interest. The curve bends upward and pulls away from the line.",
         "caption": "Compounding bends up", "cue": {"slider": 0.06, "highlight": "gap"}},
        {"text": "Raise the rate and the gap explodes. That shaded wedge is everything compounding adds beyond your gut.",
         "caption": "Higher rate, bigger gap", "cue": {"slider": 0.12, "highlight": "gap"}},
    ],
    "exponential-decay": [
        {"text": "We start with a thousand milligrams of an isotope. Its half-life is five years.",
         "caption": "1,000 mg", "cue": {"slider": 5, "highlight": "actual"}},
        {"text": "It feels like it should fall in a straight line and be gone after two half-lives.",
         "caption": "Straight-line guess", "cue": {"slider": 5, "highlight": "intuition"}},
        {"text": "But each half-life removes half of what's left. A quarter remains, then an eighth -- a long tail that never quite reaches zero.",
         "caption": "Halving, not vanishing", "cue": {"slider": 5, "highlight": "gap"}},
        {"text": "Shorten the half-life and it drops faster, but always as a curve, never a straight line.",
         "caption": "Shorter half-life", "cue": {"slider": 3, "highlight": "actual"}},
    ],
    "monty-hall": [
        {"text": "Pick one of three doors. Behind one is a prize, so your odds are one in three.",
         "caption": "1 in 3", "cue": {"variant": 0, "settle": 0.0}},
        {"text": "The host opens a losing door and offers you the switch. Now it feels fifty-fifty.",
         "caption": "Feels 50/50", "cue": {"variant": 0, "settle": 0.5}},
        {"text": "But your first pick is still right only a third of the time, so the other door must hold the other two thirds.",
         "caption": "Switch wins 2/3", "cue": {"variant": 0, "settle": 0.6667}},
        {"text": "Run a thousand games and it's clear: switching wins about two out of three. The gut was wrong.",
         "caption": "About 67% over 1,000", "cue": {"variant": 0, "settle": 0.6667, "run": True}},
    ],
    "birthday-paradox": [
        {"text": "Twenty-three people in a room. What are the odds that two of them share a birthday?",
         "caption": "23 people", "cue": {"variant": 0, "settle": 0.0}},
        {"text": "Against three hundred sixty-five days, twenty-three feels tiny -- maybe six percent.",
         "caption": "Feels ~6%", "cue": {"variant": 0, "settle": 0.063}},
        {"text": "But you're not matching one person -- you're matching every pair. Twenty-three people make two hundred fifty-three pairs.",
         "caption": "253 pairs", "cue": {"variant": 0, "settle": 0.3}},
        {"text": "Count all the pairs and the real chance is just over half. Fill rooms again and again and it holds.",
         "caption": "About 51%", "cue": {"variant": 0, "settle": 0.507, "run": True}},
    ],
    "binary-search": [
        {"text": "A sorted list of thirty-two items. We're hunting for the value twenty-two.",
         "caption": "Find 22 in 32", "cue": {"step": 0}},
        {"text": "Check the middle. It's too low, so throw away the entire bottom half in a single move.",
         "caption": "Halve it", "cue": {"step": 1}},
        {"text": "Check the middle of what's left, and halve again. Each guess deletes half the survivors.",
         "caption": "Halve again", "cue": {"step": 2}},
        {"text": "Five halvings is all it takes here -- and a list of a million would need only about twenty.",
         "caption": "Found in ~5", "cue": {"step": 5}},
    ],
    "sorting-race": [
        {"text": "Two ways to sort the same two hundred fifty-six items. They look similar -- until you count the work.",
         "caption": "256 items", "cue": {"n": 256, "focus": "both"}},
        {"text": "Merge sort needs about n log n comparisons. It finishes almost instantly.",
         "caption": "Merge: ~2,048", "cue": {"n": 256, "focus": "merge"}},
        {"text": "Bubble sort needs about n squared comparisons. It's still grinding away.",
         "caption": "Bubble: ~32,640", "cue": {"n": 256, "focus": "bubble"}},
        {"text": "That's roughly sixteen times more work here, and the gap only widens as the list grows.",
         "caption": "About 16x more", "cue": {"n": 256, "focus": "both"}},
    ],
    "recursion-fib": [
        {"text": "To compute fib of five the naive way, we call fib of four and fib of three.",
         "caption": "fib(5)", "cue": {"n": 5, "memo": False}},
        {"text": "Each of those splits again, and the same subproblems show up over and over across the tree.",
         "caption": "Repeated work", "cue": {"n": 5, "memo": False}},
        {"text": "fib of five alone makes fifteen calls. fib of fifteen makes nearly two thousand.",
         "caption": "15 calls", "cue": {"n": 5, "memo": False}},
        {"text": "Memoize -- remember each answer once -- and every repeated call disappears. Exponential collapses to linear.",
         "caption": "Memoized", "cue": {"n": 5, "memo": True}},
    ],
    "loan-amortization": [
        {"text": "A twenty-thousand-dollar loan, paid off in equal monthly payments over fifteen years.",
         "caption": "$20,000 · 15 yr", "cue": {"slider": 0.06, "highlight": "actual"}},
        {"text": "You might picture the balance falling in a straight line down to zero.",
         "caption": "Straight-line guess", "cue": {"slider": 0.06, "highlight": "intuition"}},
        {"text": "But early payments are mostly interest, so the balance drops slowly at first and stays above the straight line.",
         "caption": "Interest-heavy early", "cue": {"slider": 0.06, "highlight": "gap"}},
        {"text": "Raise the rate and the gap widens -- even more of every early payment goes to interest, not principal.",
         "caption": "Higher rate, bigger gap", "cue": {"slider": 0.09, "highlight": "gap"}},
    ],
    "base-rates": [
        {"text": "A disease affects two percent of people. A test catches ninety percent of true cases.",
         "caption": "2% sick · 90% test", "cue": {"variant": 0, "settle": 0.0}},
        {"text": "You test positive, and it feels like a ninety percent chance you're sick.",
         "caption": "Feels 90%", "cue": {"variant": 0, "settle": 0.90}},
        {"text": "But among a hundred healthy people, ten still test positive. Those false alarms swamp the handful of real cases.",
         "caption": "False alarms pile up", "cue": {"variant": 0, "settle": 0.4}},
        {"text": "Run the patients: of everyone who tests positive, only about one in six is actually sick.",
         "caption": "≈ 16% actually sick", "cue": {"variant": 0, "settle": 0.155, "run": True}},
    ],
    "hashing-collisions": [
        {"text": "Eight keys dropped into fifty buckets. Plenty of room -- a collision feels unlikely.",
         "caption": "8 keys, 50 buckets", "cue": {"variant": 0, "settle": 0.0}},
        {"text": "Comparing each key against the buckets, you'd guess maybe one chance in six.",
         "caption": "Feels ~16%", "cue": {"variant": 0, "settle": 0.16}},
        {"text": "But it's every PAIR of keys that can collide, and eight keys make twenty-eight pairs.",
         "caption": "28 pairs", "cue": {"variant": 0, "settle": 0.3}},
        {"text": "Fill the table again and again: nearly half the time two keys clash. About the square root of the buckets is all it takes.",
         "caption": "≈ 47%", "cue": {"variant": 0, "settle": 0.47, "run": True}},
    ],
    "big-o": [
        {"text": "Algorithm A grows like n squared. Algorithm B runs in a hundred times n.",
         "caption": "n² vs 100·n", "cue": {"slider": 100, "highlight": "actual"}},
        {"text": "For small inputs, B's big constant makes it the slower one -- its straight line sits above the curve.",
         "caption": "B slower at first", "cue": {"slider": 100, "highlight": "intuition"}},
        {"text": "They meet exactly where n equals the constant: at n of a hundred.",
         "caption": "Crossover at n=100", "cue": {"slider": 100, "highlight": "actual"}},
        {"text": "Past the crossover, n squared rockets away. A worse growth class always wins eventually, whatever the constant.",
         "caption": "Growth class wins", "cue": {"slider": 200, "highlight": "actual"}},
    ],
    "law-of-large-numbers": [
        {"text": "A fair coin just came up heads eight of its last ten flips. It feels like it's on a hot streak.",
         "caption": "8 of 10 heads", "cue": {"variant": 0, "settle": 0.0}},
        {"text": "Tempting to expect more heads ahead -- maybe seventy percent, riding the streak.",
         "caption": "Feels ~70%", "cue": {"variant": 0, "settle": 0.70}},
        {"text": "But the coin has no memory. Each new flip is still fifty-fifty, no matter what just happened.",
         "caption": "No memory", "cue": {"variant": 0, "settle": 0.5}},
        {"text": "Flip it ten thousand more times and the rate settles right back to fifty percent.",
         "caption": "Back to 50%", "cue": {"variant": 0, "settle": 0.5, "run": True}},
    ],
    "expected-value": [
        {"text": "A bet: win eighty dollars forty percent of the time, otherwise lose forty.",
         "caption": "Win $80 / lose $40", "cue": {"settle": 0}},
        {"text": "The upside is tempting -- it feels like you're playing for eighty dollars.",
         "caption": "Feels like $80", "cue": {"settle": 80}},
        {"text": "Averaging the two outcomes evenly lands at twenty -- but they aren't equally likely.",
         "caption": "Not a coin flip", "cue": {"settle": 20}},
        {"text": "Weight each by its probability and the real expected value is just eight dollars a play. Run a thousand and the average lands there.",
         "caption": "EV = $8", "cue": {"settle": 8, "run": True}},
    ],
    "minimax": [
        {"text": "The maximizer has three moves, and each leads to the minimizer's three replies.",
         "caption": "Three moves", "cue": {"show": "leaves"}},
        {"text": "Grab the biggest leaf -- a nine -- and you'll be disappointed: the minimizer simply won't allow it.",
         "caption": "Not the 9", "cue": {"show": "leaves"}},
        {"text": "Back up each move by its WORST reply: two, one, and four.",
         "caption": "Min of each move", "cue": {"show": "backup"}},
        {"text": "The maximizer then takes the best of those worsts -- four backs up to the root.",
         "caption": "Root = 4", "cue": {"show": "backup"}},
    ],
    "alpha-beta": [
        {"text": "Same tree. Alpha-beta scans left to right, hunting the same answer with less work.",
         "caption": "Scan left to right", "cue": {"show": "leaves"}},
        {"text": "After the first move it has secured a value of two. The next move's reply drops to one -- already worse.",
         "caption": "Already worse", "cue": {"show": "leaves"}},
        {"text": "So the rest of that branch can't change the root. Alpha-beta skips it entirely.",
         "caption": "Prune it", "cue": {"show": "prune"}},
        {"text": "It reaches the same root value, four, but evaluates only eight leaves instead of all nine.",
         "caption": "8 of 9 leaves", "cue": {"show": "prune"}},
    ],
    "supply-demand": [
        {"text": "Demand slopes down: the cheaper it is, the more buyers want.",
         "caption": "Demand", "cue": {"mode": "equilibrium", "highlight": "demand"}},
        {"text": "Supply slopes up: a higher price draws out more sellers.",
         "caption": "Supply", "cue": {"mode": "equilibrium", "highlight": "supply"}},
        {"text": "It's tempting to find where demand hits zero -- the most anyone would pay. But the market doesn't clear there.",
         "caption": "Not the choke price", "cue": {"mode": "equilibrium", "highlight": "choke"}},
        {"text": "The market clears where the two curves cross: the price that balances what buyers want with what sellers offer.",
         "caption": "Equilibrium", "cue": {"mode": "equilibrium", "highlight": "cross"}},
    ],
    "tax-incidence": [
        {"text": "Start at the equilibrium, where supply meets demand.",
         "caption": "Before the tax", "cue": {"mode": "tax", "highlight": "cross"}},
        {"text": "Add a per-unit tax, and it feels like buyers simply pay the whole thing.",
         "caption": "Buyer pays all?", "cue": {"mode": "tax", "highlight": "wedge"}},
        {"text": "But the tax opens a wedge: the buyer's price rises while the seller's price falls. Both give something up.",
         "caption": "A shared wedge", "cue": {"mode": "tax", "highlight": "buyer"}},
        {"text": "The split follows the slopes -- the steeper, more inelastic side bears the larger share, whoever the tax is levied on.",
         "caption": "Slopes decide", "cue": {"mode": "tax", "highlight": "seller"}},
    ],
    "prisoners-dilemma": [
        {"text": "Two players, each can cooperate or defect, with these payoffs.",
         "caption": "The matrix", "cue": {"highlight": "none"}},
        {"text": "If the other cooperates, you do even better by defecting -- grabbing the temptation payoff.",
         "caption": "Defect beats cooperate", "cue": {"highlight": "temptation"}},
        {"text": "If the other defects, defecting still beats being the sucker. So defecting wins either way -- it dominates.",
         "caption": "Dominant strategy", "cue": {"highlight": "defect-row"}},
        {"text": "Both players reason the same way, so both defect and land on the punishment -- worse than if they'd cooperated.",
         "caption": "Both lose", "cue": {"highlight": "nash"}},
    ],
    "grid-search": [
        {"text": "Find the shortest path on a grid where you can only step up, down, left, or right.",
         "caption": "4 directions", "cue": {"radius": 0, "highlight": "flood"}},
        {"text": "Breadth-first search explores outward in rings: every cell one step away, then two, then three.",
         "caption": "Rings outward", "cue": {"radius": 4, "highlight": "flood"}},
        {"text": "The first time a ring touches the goal, that's the shortest path -- here, twelve steps.",
         "caption": "Reached in 12", "cue": {"radius": 12, "highlight": "path"}},
        {"text": "It feels like a diagonal would be shorter, but you can't move diagonally. The path is the columns plus the rows.",
         "caption": "No diagonal", "cue": {"radius": 12, "highlight": "diagonal"}},
    ],
    "central-limit": [
        {"text": "Roll one die and the outcome is flat -- every face equally likely.",
         "caption": "One die: flat", "cue": {"n": 1}},
        {"text": "Average two dice and the middle becomes more likely. Average more, and a bell appears.",
         "caption": "Averages cluster", "cue": {"n": 2}},
        {"text": "Whatever shape the population had, the distribution of sample means becomes normal.",
         "caption": "Means go normal", "cue": {"n": 9}},
        {"text": "And the bell narrows as you average more -- the spread shrinks like the square root of the sample size, not the size itself.",
         "caption": "Spread ~ 1/√n", "cue": {"n": 16}},
    ],
    "regression-mean": [
        {"text": "Plot a noisy test against its retest. Most points scatter around the average.",
         "caption": "Test vs retest", "cue": {"highlight": "cloud"}},
        {"text": "Pick the top scorer. Part of that score was skill, and part was a lucky day.",
         "caption": "An extreme", "cue": {"highlight": "extreme"}},
        {"text": "The luck doesn't repeat, so on the retest they drift back toward the mean -- below the dashed equal-scores line.",
         "caption": "Drifts back", "cue": {"highlight": "regress"}},
        {"text": "Not all the way to the mean, just by the share that was luck. That's regression to the mean.",
         "caption": "Partway back", "cue": {"highlight": "regress"}},
    ],
    "projectile": [
        {"text": "Throw a ball at thirty degrees and it arcs out to here.",
         "caption": "30° arc", "cue": {"slider": 30, "highlight": "actual"}},
        {"text": "Throw at sixty degrees -- a steeper, higher arc -- and it lands in exactly the same spot.",
         "caption": "60° lands together", "cue": {"slider": 30, "highlight": "gap"}},
        {"text": "Range is symmetric around forty-five degrees, so theta and ninety-minus-theta always match.",
         "caption": "Symmetric at 45", "cue": {"slider": 35, "highlight": "gap"}},
        {"text": "Forty-five degrees is the single best angle -- the very top of that symmetry, giving the maximum distance.",
         "caption": "45° is farthest", "cue": {"slider": 45, "highlight": "actual"}},
    ],
    "mcts": [
        {"text": "Four moves, each with a win rate from past simulations. Greedy play just takes the highest.",
         "caption": "Win rates", "cue": {"mode": "exploit"}},
        {"text": "But a move tried only a few times is uncertain -- its true value could be much higher.",
         "caption": "Few visits, unsure", "cue": {"mode": "exploit"}},
        {"text": "UCB1 adds an exploration bonus on top of the win rate, bigger for the moves it has tried least.",
         "caption": "+ exploration bonus", "cue": {"mode": "ucb"}},
        {"text": "So MCTS sometimes picks a lower-win-rate move it hasn't explored enough -- not random, but deliberately curious.",
         "caption": "Explore the unsure", "cue": {"mode": "ucb"}},
    ],
    "cipher": [
        {"text": "A Caesar cipher shifts every letter by the same amount. At a glance it looks like noise.",
         "caption": "Looks like noise", "cue": {"shift": 0}},
        {"text": "But the letter frequencies leak through: one letter shows up far more often than the rest.",
         "caption": "A spike leaks", "cue": {"shift": 0}},
        {"text": "English's most common letter is E. Slide the alphabet until that spike lines up with E.",
         "caption": "Align to E", "cue": {"shift": 4}},
        {"text": "When the bars match English, you've found the shift -- the cipher hid nothing.",
         "caption": "Shift found", "cue": {"shift": 7}},
    ],
}
